name: Docker Runner

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: self-hosted
    environment: production
    defaults:
      run:
        secrets: inherit

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: sudo docker compose up -d --build

      - name: Cleanup Unused Images
        run: sudo docker image prune -f