name: Docker Runner

on:
  push:
    branches: [main]

jobs:  
  run:
    secrets: inherit
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}

        run: sudo docker compose up -d --build

      - name: Cleanup Unused Images
        run: sudo docker image prune -f