name: Docker Runner

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: sudo docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}

      - name: Cleanup Unused Images
        run: sudo docker image prune -f

      - name: Cleanup Unused Containers
        run: sudo docker container prune -f