name: Docker Runner

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Container
        run: |
          sudo docker-compose up -d --build \
            -e TOKEN="${{ secrets.TOKEN }}" \
            -e GUILD_ID="${{ secrets.GUILD_ID }}"

      - name: Cleanup Unused Images
        run: sudo docker image prune -f
