name: Docker Runner

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Print Environment Variables
        run: |
          echo "TOKEN: $TOKEN"
          echo "GUILD_ID: $GUILD_ID"
          

      - name: Run Container
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
        run: sudo docker compose up -d --build

      - name: Cleanup Unused Images
        run: sudo docker image prune -f