name: Docker Runner

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: sudo docker run -e TOKEN=${{ secrets.TOKEN }} -e GUILD_ID=${{ secrets.GUILD_ID }} -d xhos/bear_bot

      - name: Cleanup Unused Images
        run: sudo docker image prune -f