name: Docker Runner

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Container
        run: |
          export TOKEN="${{ secrets.TOKEN }}"
          export GUILD_ID="${{ secrets.GUILD_ID }}"
          sudo docker-compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}

      - name: Cleanup Unused Images
        run: sudo docker image prune -f